<a href="https://colab.research.google.com/github/Saicharanchearla/2303A510I8_ADMLAB/blob/main/NLP_LAB2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

marks = np.array([
    [85, 78, 92],
    [76, 88, 90],
    [90, 94, 89],
    [67, 74, 70],
    [88, 82, 91]
])

print("Student Marks (5 students × 3 subjects):\n", marks)


Student Marks (5 students × 3 subjects):
 [[85 78 92]
 [76 88 90]
 [90 94 89]
 [67 74 70]
 [88 82 91]]


In [2]:
avg_per_student = np.mean(marks, axis=1)
print("\nAverage marks per student:\n", avg_per_student)

min_per_student = np.min(marks, axis=1)
print("\nMinimum marks per student:\n", min_per_student)

max_per_student = np.max(marks, axis=1)
print("\nMaximum marks per student:\n", max_per_student)



Average marks per student:
 [85.         84.66666667 91.         70.33333333 87.        ]

Minimum marks per student:
 [78 76 89 67 82]

Maximum marks per student:
 [92 90 94 74 91]


In [3]:
selected_students = marks[[1, 3]]
print("\nMarks of Student 2 and Student 4:\n", selected_students)



Marks of Student 2 and Student 4:
 [[76 88 90]
 [67 74 70]]


In [4]:
high_achievers = avg_per_student > 80
print("\nStudents with average marks > 80:\n", high_achievers)

print("\nMarks of students with average > 80:\n", marks[high_achievers])



Students with average marks > 80:
 [ True  True  True False  True]

Marks of students with average > 80:
 [[85 78 92]
 [76 88 90]
 [90 94 89]
 [88 82 91]]


In [5]:
subject_wise = marks.T
print("\nSubject-wise marks (Subjects × Students):\n", subject_wise)

avg_subject = np.mean(subject_wise, axis=1)
print("\nAverage marks per subject:\n", avg_subject)



Subject-wise marks (Subjects × Students):
 [[85 76 90 67 88]
 [78 88 94 74 82]
 [92 90 89 70 91]]

Average marks per subject:
 [81.2 83.2 86.4]


In [6]:
print("\n--- Analysis ---")
print("• Student 3 has the highest average and excels in all subjects.")
print("• Students 1, 3, and 5 scored above 80 on average – strong performers.")
print("• Math and English have higher overall averages than Science.")
print("• Student 4 has the lowest scores, indicating need for improvement.")



--- Analysis ---
• Student 3 has the highest average and excels in all subjects.
• Students 1, 3, and 5 scored above 80 on average – strong performers.
• Math and English have higher overall averages than Science.
• Student 4 has the lowest scores, indicating need for improvement.
